export const universityAction = {
  GET_ADMIN_NUMBER: 'GET_ADMIN_NUMBER',
  SET_ADMIN_NUMBER: 'SET_ADMIN_NUMBER',
  ADD_NEW_ADMIN: 'ADD_NEW_ADMIN',
  REMOVE_ADMIN: 'REMOVE_ADMIN',
  GET_ALL_ADMINS: 'GET_ALL_ADMINS',
  SET_ADMINS_LIST: 'SET_ADMINS_LIST',
};

export const userAction = {
  USER_LOGGED_IN: 'USER_LOGGED_IN',
  USER_UPDATED: 'USER_UPDATED',
  USER_LOGGED_OUT: 'USER_LOGGED_OUT',
  USER_TRY_LOGIN: 'USER_TRY_LOGIN',
  METAMASK_NOT_FOUND: 'METAMASK_NOT_FOUND',
  EDIT_ADDRESS: 'EDIT_ADDRESS',
};
